title: DataCruncher
description: DataCruncher is a Data Quality Firewall suite.
It includes an advanced UI for schema definition, governance, real-time data monitoring, ETL, business rules, automatic forms generation, alerting, mobile interface.
google_analytics: UA-49109406-1
show_downloads: true
theme: jekyll-theme-architect

gems:
  - jekyll-mentions
